### ISSUE TITLE
Add ability to read mysql password from docker secret

### ISSUE THREAD

**Issue by AndrewSav** [puppetlabs/europa#14]
In [this thread](https://github.com/moby/moby/issues/30866) we learn that

>Keeping secrets out of environment variables is a deliberate design decision and is not going to be reversed.

Similar to https://github.com/docker-library/mariadb/issues/131, could we have europa read mysql password from a secret?

**Comment by doct15** [comment]
I took a look at Docker secrets and this should work today.

I am confident that Kubernetes secrets would work as expected today since they can be treated as env variables in the container. Only available in that container.

**Comment by thrnio** [comment]
This should actually already be possible, as @doct15 mentioned. It's not well-documented, but you can pass the environment variable config as a JSON file instead. You have to pass all the database configuration details as a file, though—you can't mix and match. The format looks like this:

~~~json
{
  "dbEndpoint": "mysql://dbhost.example.com:3306/europa",
  "dbUser": "root",
  "dbPass": "hunter2"
}
~~~

You can store that as a Docker secret, then mount it into the container as a file (e.g., `/etc/europa-config.json`). You can then have Europa load that configuration by modifying the `CMD` at runtime with the `--config` flag; e.g., adding this to your Docker Compose file:

~~~
command: ["./run", "--config", "/etc/europa-config.json"]
~~~

We're working to update and improve the docs, so I'll make sure that this gets added.
