### ISSUE TITLE
Alternate ports

### ISSUE THREAD

**Issue by tamarintech** [puppetlabs/europa#44]
I wanted to do some testing and placed distelli/europa:latest on alternate ports. The result is this:

```
$ docker pull docker0.colo.networkedinsights.com:1080/myproject
Using default tag: latest
Trying to pull repository docker0.colo.networkedinsights.com:1080/myproject ... 
Get https://docker0.colo.networkedinsights.com:1080/v1/_ping: http: server gave HTTP response to HTTPS client
```

```
$ docker pull dockerhost:10443/myproject
Using default tag: latest
Trying to pull repository dockerhost:10443/myproject ... 
Get http://dockerhost:10443/v2/token?scope=repository%3Amyproject%3Apull&service=distelli.docker-registry: EOF
```

The UI works flawlessly. I cannot push, pull, or login. If I move the container to 80/443 it seems to work fine. This is obviously an issue with the way I'm wanting to test including this product in a demonstration, but I was hoping maybe there was a fix or explanation as to why the login and pull results in the http://docker failure. I haven't tried proxying yet, but any advice would be great on if it would be possible to run on a different set of ports and/or a different path (ie: prefixed https://dockerhost/europa-latest).

**Comment by brimworks** [comment]
Typically you need to configure your docker engine with the trusted registries parameter... perhaps you simply did not specify the trusted registries parameter with this alternative port number?

**Comment by tamarintech** [comment]
Hm? I might be misunderstanding you.

This isn't configured as an insecure registry and has a certificate. There shouldn't be anything else required to pull and push to/from it. If I were to do the same with docker-distribution there is no additional configuration - I should be able to log in and pull right away.

**Comment by brimworks** [comment]
Oh, my bad. There is an issue similar to this error when an untrusted certificate is used. It seems that docker is trying the wrong protocol given the port number your using. Specifically, I'm assuming that 1080 port is your non-secure port, but the error message indicates that docker engine is trying to use the "https" protocol... and when using the secure port 10443 the error indicates it tried to use the insecure port "http"... which is an error that occurs typically when certificate validation fails.

...so I'm not sure why docker engine is having this behavior. I would look in your docker engine logs.

**Comment by thrnio** [comment]
Ah, this is actually an issue that's fixed in master, we just haven't put out a new image recently enough. Specifically, there was a bug in the protocol identification code causing it to erroneously think that it was being accessed over HTTP under certain conditions, and so it's telling the docker client to get a session token over HTTP but using the HTTPS port, which naturally doesn't work.

**Comment by danieldreier** [comment]
@tamarintech I've promoted our current build to `distelli/europa:latest`. It should include the fix @thrnio mentioned. Would you please try again and report back if it's working for you?

**Comment by tamarintech** [comment]
```
$ docker login https://dockerhost:10443
Username: TOKEN                     
Password: 
Login Succeeded
```

Perfect! :+1:

**Comment by danieldreier** [comment]
Awesome! Thanks @tamarintech, please let us know if you run into any future issues.
