### ISSUE TITLE
Configurable URLs and ports

### ISSUE THREAD

**Issue by tamarintech** [puppetlabs/europa#46]
There doesn't seem to be a way to configure the ports or URLs for PCR.

Example:
A user wants to use PCR as a _drop-in replacement_ for docker-distribution which normally uses port 5000. Behind a proxy or port map the UI will display the incorrect URL in the `docker pull ...` hints.

Configurable paths/prefix, port, and hostname would be awesome.

**Comment by danieldreier** [comment]
@tamarintech I've created a ticket on our internal system to add configurable ports. I think that part should be pretty straightforward, and I understand the use case.

Can you help me understand the use case(s) you see for configurable prefixes? I've never run into needing that so it would help me understand what problem is being solved.

**Comment by tamarintech** [comment]
Sounds great. Thanks!


As for prefixes, it would be great to be able to compose the UI/webapp portion of PCR and other tools into routing. 
Example:
bigapp.myco/logging -> Kibana
bigapp.myco/metrics -> Grafana
bigapp.myco/registry -> PCR

This is probably not nearly as useful for most people as the port and hostname fixups. The example above is probably mostly vanity :) but there are also usages for people who may want to have a /development or /tenant environment to consolidate images into but that don't quite fit into "teams" or similar concepts.

**Comment by danieldreier** [comment]
@tamarintech that makes sense. Thanks for explaining the use case. The two features you're requesting (configurable ports, prefixes) are in different parts of the codebase, so I'm creating two different backend tickets on our side. I think ports will be easier, and are also something I've been wanting because it would be helpful while developing, so I'll prioritize that functionality.

**Comment by danieldreier** [comment]
@tamarintech I believe you can solve your use case simply by mapping the docker port differently - we don't actually need to change what port PCR binds to inside the Docker container.

For example:
```
docker run --rm --name europa -e EUROPA_DB_ENDPOINT=mysql://172.17.0.2:3306/pcr -e EUROPA_DB_USER=pcr -e EUROPA_DB_PASS=hunter2 --link mysql:mysql -p 5000:80 pcr:latest
```

**Comment by tamarintech** [comment]
Certainly, but.... the UI (the pull hints for example) would be inconsistent and confusing.

In an earlier example I mapped to 10443 for a demo and everything worked as expected except the UI did not reflect the change.

**Comment by thrnio** [comment]
@tamarintech When I run the container in the way @danieldreier specified, I see `localhost:5000` in the pull hints. That comes from the "DNS Name" configured in the SSL settings, if set, or the Host header from the request, if unset. Do you have the "DNS Name" set? The name of that field may be a bit confusing, but that value is used as-is to generate those commands, so if 

1. you're running on anything other than port 80/443,
2. you have a value set for "DNS Name", and
3. you don't have the port included in the "DNS Name"

that could be what is causing your commands to be wrong.

**Comment by tamarintech** [comment]
I see. I didn't try adding a port to the DNS. Sounds good. Thanks!
